"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Bot,ChevronDown,Circle,Download,Music2,Pause,Play,Plus,Save,Sparkles,Square,Trash2,Volume2} from "lucide-react";

type Note={pitch:number;step:number;length:number;velocity:number};
type Track={id:string;name:string;instrument:string;volume:number;notes:Note[]};
const pitches=["C5","B4","A#4","A4","G#4","G4","F#4","F4","E4","D#4","D4","C4"];
const initialTracks:Track[]=[{id:"lead",name:"Lead",instrument:"Pulse",volume:0.85,notes:[{pitch:0,step:0,length:2,velocity:1},{pitch:2,step:4,length:2,velocity:.9},{pitch:4,step:8,length:2,velocity:.85},{pitch:7,step:12,length:4,velocity:.95}]},{id:"bass",name:"Bass",instrument:"Triangle",volume:.65,notes:[{pitch:8,step:0,length:4,velocity:.8},{pitch:10,step:8,length:4,velocity:.75}]}];
function midiFromRow(row:number){return 72-row}
export default function Home(){
 const [bpm,setBpm]=useState(128),[tracks,setTracks]=useState(initialTracks),[active,setActive]=useState("lead"),[playing,setPlaying]=useState(false),[step,setStep]=useState(0),[aiOpen,setAiOpen]=useState(true),[prompt,setPrompt]=useState(""),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const audio=useRef<AudioContext|null>(null); const timer=useRef<number|null>(null);
 const current=tracks.find(t=>t.id===active)!;
 const allNotes=useMemo(()=>tracks.flatMap(t=>t.notes.map(n=>({...n,track:t}))),[tracks]);
 useEffect(()=>{const raw=localStorage.getItem("onlinetrack-project");if(raw)try{setTracks(JSON.parse(raw).tracks);setBpm(JSON.parse(raw).bpm)}catch{}},[]);
 useEffect(()=>()=>{if(timer.current)window.clearInterval(timer.current);audio.current?.close()},[]);
 const tone=(freq:number,duration:number,velocity:number,instrument:string)=>{if(!audio.current)audio.current=new AudioContext();const c=audio.current,o=c.createOscillator(),g=c.createGain();o.type=instrument==="Triangle"?"triangle":instrument==="Saw":"square";o.frequency.value=freq;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(Math.max(.02,velocity*.12),c.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+duration+.02)};
 const toggle=()=>{if(playing){if(timer.current)window.clearInterval(timer.current);timer.current=null;setPlaying(false);return} setPlaying(true);let s=0;const tick=()=>{setStep(s%16);for(const n of allNotes.filter(x=>x.step===s%16)){const midi=midiFromRow(n.pitch);tone(440*Math.pow(2,(midi-69)/12),Math.min(.5,n.length*(60/bpm/4)),n.velocity,n.track.instrument)}s++};tick();timer.current=window.setInterval(tick,60000/bpm/4)};
 const addNote=(row:number,col:number)=>setTracks(ts=>ts.map(t=>t.id!==active?t:{...t,notes:t.notes.some(n=>n.pitch===row&&n.step===col)?t.notes.filter(n=>!(n.pitch===row&&n.step===col)):[...t.notes,{pitch:row,step:col,length:1,velocity:.9}]}));
 const save=()=>{localStorage.setItem("onlinetrack-project",JSON.stringify({bpm,tracks}));setSaved(true);setTimeout(()=>setSaved(false),1400)};
 const addTrack=()=>setTracks(ts=>[...ts,{id:crypto.randomUUID(),name:"Track "+(ts.length+1),instrument:"Pulse",volume:.7,notes:[]}]);
 const ask=async()=>{if(!prompt.trim())return;setBusy(true);setAnswer("");const r=await fetch("/api/ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt,project:{bpm,tracks}})});if(!r.ok){setAnswer("AI is not configured yet. Add AI_GATEWAY_API_KEY in your environment.");setBusy(false);return}const reader=r.body?.getReader();const dec=new TextDecoder();if(reader){while(true){const {done,value}=await reader.read();if(done)break;setAnswer(x=>x+dec.decode(value,{stream:true}))}}setBusy(false)};
 return <main className="app"><header><div className="brand"><div className="logo"><Music2 size={20}/></div><div><b>OnlineTracker</b><span>music workstation</span></div></div><div className="transport"><button onClick={()=>setStep(0)} title="Reset"><Square size={15}/></button><button className="play" onClick={toggle}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><div className="tempo"><span>BPM</span><input type="number" value={bpm} min={40} max={300} onChange={e=>setBpm(+e.target.value)}/></div></div><div className="actions"><button onClick={save}><Save size={16}/>{saved?"Saved":"Save"}</button><button><Download size={16}/>Export</button></div></header>
 <div className="workspace"><aside className="tracks"><div className="panel-title"><span>TRACKS</span><button onClick={addTrack}><Plus size={15}/></button></div>{tracks.map(t=><button key={t.id} className={"track "+(active===t.id?"selected":"")} onClick={()=>setActive(t.id)}><div className="track-icon"><Circle size={9}/></div><div className="track-name"><b>{t.name}</b><span>{t.instrument}</span></div><Volume2 size={14}/></button>)}<div className="hint">Click cells to place notes.<br/>Press play to hear your pattern.</div></aside>
 <section className="editor"><div className="editor-head"><div><b>{current.name}</b><span> · {current.instrument}</span></div><div className="pattern">PATTERN 01 <ChevronDown size={14}/></div></div><div className="grid-wrap"><div className="keys">{pitches.map(p=><div key={p}>{p}</div>)}</div><div className="grid">{pitches.map((_,r)=><div className="row" key={r}>{Array.from({length:16},(_,c)=>{const n=current.notes.find(x=>x.pitch===r&&x.step===c);return <button key={c} onClick={()=>addNote(r,c)} className={"cell "+(c%4===0?"beat ":"")+(n?"note ":"")+(playing&&step===c?"now":"")}><span>{n?"●":""}</span></button>})}</div>)}</div></div><div className="timeline">{Array.from({length:16},(_,i)=><span key={i}>{i+1}</span>)}</div></section>
 <aside className={"ai "+(aiOpen?"open":"")}><div className="ai-head"><div className="ai-title"><div className="spark"><Sparkles size={16}/></div><div><b>Track AI</b><span>creative copilot</span></div></div><button onClick={()=>setAiOpen(!aiOpen)}><Bot size={17}/></button></div>{aiOpen&&<div className="ai-body"><div className="suggestions"><button onClick={()=>setPrompt("Create a catchy 4-bar melody for this track.")}>Create melody</button><button onClick={()=>setPrompt("Suggest a bassline that fits this track.")}>Suggest bassline</button><button onClick={()=>setPrompt("Give me a chord progression for this idea.")}>Add chords</button></div>{answer&&<div className="answer">{answer}</div>}<div className="chat"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask the AI about your track..." onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}}/><button onClick={ask} disabled={busy}>{busy?"...":"Ask"}</button></div><div className="ai-note"><Sparkles size={13}/> AI sees your BPM, tracks and notes.</div></div>}</aside></div><footer><span>ONLINE · LOCAL PROJECT</span><span>{tracks.length} tracks · {allNotes.length} notes · {bpm} BPM</span></footer></main>}